import { describe, expect, it } from "vitest";
import type { CodeGenContext } from "#src/core/codegen/context.js";
import { createFastGen, generateFast } from "#src/core/codegen/fast-path.js";
import { createSlowGen, generateSlow } from "#src/core/codegen/slow-path.js";
import { generateValidator } from "#src/core/codegen/index.js";
import type { SchemaIR, StringIR } from "#src/core/types.js";

/**
 * The orchestrator (codegen/index.ts) creates both FastGen and SlowGen from the
 * same CodeGenContext. This test verifies the invariant: fast-path and slow-path
 * share counter and preamble, so generated variable names never collide.
 */
describe("shared CodeGenContext between fast-path and slow-path", () => {
  it("fast and slow paths share the same counter — no name collisions", () => {
    const ctx: CodeGenContext = {
      preamble: [],
      counter: 0,
      fnName: "safeParse_test",
      regexCache: new Map(),
      mode: "inline",
      usedHelpers: new Set(),
    };

    // Fast-path runs first (matches orchestrator order)
    const fg = createFastGen("input", ctx);
    const ir: StringIR = {
      type: "string",
      checks: [{ kind: "string_format", format: "email" }],
    };
    const fastExpr = generateFast(ir, fg);
    expect(fastExpr).not.toBeNull();

    const counterAfterFast = ctx.counter;
    expect(counterAfterFast).toBeGreaterThan(0);

    // Slow-path runs second with the SAME ctx
    const sg = createSlowGen("__data", "__data", "[]", "__issues", ctx);
    generateSlow(ir, sg);

    const counterAfterSlow = ctx.counter;
    // With regex dedup, slow path reuses the fast path's email regex variable
    // so counter may not increase if the only new operation was a deduped regex
    expect(counterAfterSlow).toBeGreaterThanOrEqual(counterAfterFast);

    // All preamble variable names should be unique
    const varNames = ctx.preamble
      .map((line) => {
        const match = /var (\w+)=/.exec(line);
        return match?.[1];
      })
      .filter(Boolean);
    const uniqueNames = new Set(varNames);
    expect(varNames.length).toBe(uniqueNames.size);
  });

  it("preamble entries from both paths are interleaved correctly", () => {
    const ctx: CodeGenContext = {
      preamble: [],
      counter: 0,
      fnName: "safeParse_test",
      regexCache: new Map(),
      mode: "inline",
      usedHelpers: new Set(),
    };

    const fg = createFastGen("input", ctx);
    const sg = createSlowGen("__data", "__data", "[]", "__issues", ctx);

    // Generate fast for enum (uses Set preamble)
    const enumIR = { type: "enum" as const, values: ["a", "b", "c", "d", "e", "f"] };
    const fastCode = generateFast(enumIR, fg);
    const preambleAfterFast = ctx.preamble.length;
    expect(preambleAfterFast).toBe(1);

    // The slow path for the SAME enum reuses that declaration rather than
    // emitting the value list a second time.
    const slowCode = generateSlow(enumIR, sg);
    expect(ctx.preamble.length).toBe(preambleAfterFast);
    const setName = /(__set_enum_\d+)/.exec(fastCode ?? "")?.[1];
    expect(setName).toBeTruthy();
    expect(slowCode).toContain(setName as string);

    // A DIFFERENT value list still appends, so the shared context keeps growing.
    generateSlow({ type: "enum" as const, values: ["x", "y", "z", "w", "v", "u"] }, sg);
    expect(ctx.preamble.length).toBeGreaterThan(preambleAfterFast);

    // All generated preamble lines should be valid JS declarations
    for (const line of ctx.preamble) {
      expect(line).toMatch(/^var \w+=/);
    }
  });

  it("temp() from FastGen and SlowGen never produce duplicate names", () => {
    const ctx: CodeGenContext = {
      preamble: [],
      counter: 0,
      fnName: "safeParse_test",
      regexCache: new Map(),
      mode: "inline",
      usedHelpers: new Set(),
    };
    const fg = createFastGen("input", ctx);
    const sg = createSlowGen("__data", "__data", "[]", "__issues", ctx);

    const names = [fg.temp("x"), sg.temp("x"), fg.temp("x"), sg.temp("x")];
    const unique = new Set(names);
    expect(names.length).toBe(unique.size);
  });
});

/**
 * Constant preamble declarations (enum `Set`s, strict-shape key tables, file
 * mime lists) are keyed by their initializer text, so a value list reached from
 * several places — the fast check AND the slow walk, or two properties that
 * share an enum — is emitted once. Per-use emission cost 18-21% of the
 * generated bytes on enum-heavy schemas.
 */
describe("constant declarations deduplicate by value", () => {
  const enumIR = (values: string[]): SchemaIR => ({ type: "enum", values });
  const countSets = (code: string): number => code.split("new Set(").length - 1;
  const generate = (ir: SchemaIR): string => {
    const r = generateValidator(ir, "dedupe");
    return `${r.code}\n${r.functionDef}`;
  };

  it("emits one Set for an enum used by both the fast check and the slow walk", () => {
    const code = generate(enumIR(["a", "b", "c", "d", "e", "f"]));
    expect(countSets(code)).toBe(1);
  });

  it("shares one Set between two properties with identical values", () => {
    const values = ["one", "two", "three", "four", "five", "six", "seven"];
    const code = generate({
      properties: { a: enumIR(values), b: enumIR(values) },
      type: "object",
    });
    expect(countSets(code)).toBe(1);
  });

  it("keeps separate Sets for different value lists", () => {
    const code = generate({
      properties: {
        a: enumIR(["one", "two", "three", "four", "five", "six"]),
        b: enumIR(["red", "green", "blue", "cyan", "black", "white"]),
      },
      type: "object",
    });
    expect(countSets(code)).toBe(2);
  });

  it("emits one key table for a strict shape, not one per path", () => {
    const code = generate({
      properties: Object.fromEntries(
        ["id", "name", "email", "role", "active", "createdAt"].map((k) => [
          k,
          { checks: [], type: "string" } as SchemaIR,
        ]),
      ),
      strict: true,
      type: "object",
    });
    expect(code.split('{"id":1,').length - 1).toBe(1);
  });
});
